name: d8-platform
recipe: drupal8
config:
  webroot: docroot
  php: 7.2
  xdebug: true
services:
  appserver:
    config:
      conf: lando/lando_php.ini
    run:
      ## For running drush/alias commands against Acquia
      ## We assume our own local keys have been uploaded to Acquia
      - cp /user/.ssh/id_rsa /var/www/.ssh/id_rsa
      - cp /user/.ssh/id_rsa.pub /var/www/.ssh/id_rsa.pub
      - chmod 700 /var/www/.ssh
      - chmod 600 /var/www/.ssh/id_rsa
      - chmod 644 /var/www/.ssh/id_rsa.pub
      ## Set up tools for behat testing. (https://askubuntu.com/questions/510056/how-to-install-google-chrome)
    run_as_root:
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
      - apt update
      - apt -y install google-chrome-stable
      - apt -y install libnss3
      - ln -s /app /var/www/creighton
  mailhog:
    type: 'mailhog'
    hogfrom:
      - 'appserver'
tooling:
  blt:
    service: appserver
    description: Run Acquia blt commands in the lando environment
    cmd: /app/vendor/bin/blt
  ## In case SSH breaks, allow us to fix it with a lando command
  fixssh:
    service: appserver
    description: Fixes ssh issues by copying your local key files into lando and fixing permissions
    cmd:
      - cp /user/.ssh/id_rsa /var/www/.ssh/id_rsa
      - cp /user/.ssh/id_rsa.pub /var/www/.ssh/id_rsa.pub
      - chmod 700 /var/www/.ssh
      - chmod 600 /var/www/.ssh/id_rsa
      - chmod 644 /var/www/.ssh/id_rsa.pub
