cu_breadcrumbs.global_settings:
  type: config_entity
  label: 'cu breadcrumbs global config'
  mapping:
    builder:
      type: string
      label: 'Breadcrumb builder mode'

cu_breadcrumbs.settings.*:
  type: config_entity
  label: 'cu breadcrumbs config'
  mapping:
    uuid:
      type: string
      label: 'UUID'
    builder:
      type: string
      label: 'Breadcrumb builder mode'
