<?php

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\Component\Utility\Html as HtmlUtility;
use Drupal\Core\Render\Markup;
use Drupal\Component\Render\HtmlEscapedText;

function cu2019_grad_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $variables['par_id'] = $paragraph->id();
  $variables['par_type'] = $paragraph->getType();
  $variables['meh'] = "MEHHHH";
}
