<?php

/**
 * @file
 * Contains cu_breadcrumbs.module.
 * Max McCoy 3.18.2019
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\cu_breadcrumbs\Breadcrumb\CUBreadcrumbModel;

/**
 * Implements hook_help().
 */
function cu_breadcrumbs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cu_breadcrumbs module.
    case 'help.page.cu_breadcrumbs':
      return '<h3>' . t('About') . '</h3>
      <p>' . t('Facilitates the application of Home (www.creighton.edu) and custom breadcrumbs to content types.') . '</p>
      <br><h3>' . t('Use') . '</h3>
      <p>' . t('During content type creation/edit, selecting "Apply custom breadcrumb" will apply custom breadcrumbs to all content of that type.') 
      . '</p>
      <p>' . t('To add more links to the breadcrumb, navigate to Structure->Menus add a menu titled "Breadcrumbs Menu".') 
      . '</p>
      <p>' . t('Any links added to this will be appended to the default home breadcrumb in the order specified in the menu.') 
      . '</p>';
  }
}

/**
 * Implements hook_form_node_type_add_form_alter().
 */
function cu_breadcrumbs_form_node_type_add_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  add_cu_breadcrumb_chkbox($form, $form_state);
}

/**
 * Implements hook_form_node_type_edit_form_alter().
 * does essentially the same thing as the add hook
 */
function cu_breadcrumbs_form_node_type_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  add_cu_breadcrumb_chkbox($form, $form_state);
}
  
/**
 * Implements hook_form_node_type_edit_form_submit().
 */
function cu_breadcrumbs_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $attributes = ['uuid'=>$form_state->getFormObject()->getEntity()->get('uuid')
                  ,'apply'=>$form_state->getValue('cu_breadcrumbs_apply')];
  $cu_breadcrumb = new CUBreadcrumbModel();
  $cu_breadcrumb->fill($attributes);
  $cu_breadcrumb->save();
}

/**
 * Add the new checkbox to the form.
 */
function add_cu_breadcrumb_chkbox(&$form, \Drupal\Core\Form\FormStateInterface $form_state){
  // Add a checkbox to content type form w/default_value set to db value
  $form['cu_breadcrumbs_apply'] = array(
    '#type' => 'checkbox',
    '#title' => t("Apply custom breadcrumb"),
    '#default_value'=>get_cu_breadcrumbs_apply($form_state->getFormObject()
                                                          ->getEntity()
                                                          ->get('uuid')),
  );
  //add cu breadcrumbs to form submit
  $form['#submit'][] = 'cu_breadcrumbs_form_submit';
  $form['actions']['submit']['#submit'][] = 'cu_breadcrumbs_form_submit';
}

/**
 * get apply boolean from db using node_type uuid
 */
function get_cu_breadcrumbs_apply($id){
  $cu_breadcrumb = new CUBreadcrumbModel();
  $cu_breadcrumb->getById($id);
  //a lot of the time there may not be a value
  return $cu_breadcrumb->get('apply');
}