cu_hub_consumer.settings:
  type: config_object
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    hub_base_url:
      type: uri
      label: 'Hub Base URI'

cu_hub_consumer.hub_reference_type.*:
  type: config_entity
  label: 'Hub reference type'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
    source:
      type: string
      label: 'Source'
    source_configuration:
      type: cu_hub_consumer.hub_reference_source.[%parent.source]
    field_map:
      type: sequence
      label: 'Field map'
      sequence:
        type: string

cu_hub_consumer.hub_reference_source.*:
  type: mapping
  label: 'Hub reference source settings'

cu_hub_consumer.hub_reference_source.node:*:
  type: hub_reference.source.field_aware
  label: 'Node hub reference source configuration'

cu_hub_consumer.hub_reference_source.field_aware:
  type: mapping
  mapping:
    source_field:
      type: string
      label: 'Source field'
